
// courses
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAILED = 'LOAD_COURSES_FAILED';
export const LOAD_COURSES_PENDING = 'LOAD_COURSES_PENDING';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';

// single course
export const CREATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
export const DELETE_COURSES_SUCCESS = 'DELETE_COURSE_SUCCESS';


// authors
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHORS_FAILED = 'LOAD_AUTHORS_FAILED';
export const LOAD_AUTHORS_PENDING = 'LOAD_AUTHORS_PENDING';

// single author
export const UPDATE_AUTHORS_SUCCESS = 'UPDATE_AUTHORS_SUCCESS';
export const CREATE_AUTHORS_SUCCESS = 'UPDATE_AUTHORS_SUCCESS';
export const DELETE_AUTHORS_SUCCESS = 'DELETE_AUTHORS_SUCCESS';

